services:
  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - 8000:8000

  client:
    build: client
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        source: client_node_modules
        target: /app/node_modules
    ports:
      - 4321:4321
    depends_on:
      - server
  
  k6-tests:
    entrypoint: "/bin/true"
    build: k6-tests
    volumes:
      - ./k6-tests/tests:/tests
    depends_on:
      - client

volumes:
  client_node_modules:
